### ISSUE TITLE
py35 packages not uploaded to channel

### ISSUE THREAD

**Issue by goanpeca** [conda-forge/pytest-json-feedstock#1]
@jakirkham , @nicoddemus no packages were uploaded for py3X version on OSX and n py35 on Windows...

https://anaconda.org/conda-forge/pytest-json/files

:-| ?

**Comment by nicoddemus** [comment]
If you look at the [README](https://github.com/conda-forge/pytest-json-feedstock) you can see that hte builds failed in OSX and AppVeyor. Probably it was an intermittent CI failure, I just restarted the builds. If they complete the packages should be uploaded correctly.

**Comment by goanpeca** [comment]
ok thanks :-)

**Comment by goanpeca** [comment]
Windows is ok now, but OSX is busted :-|

<img width="1068" alt="screen shot 2016-10-21 at 4 05 13 pm" src="https://cloud.githubusercontent.com/assets/3627835/19610014/37c9fbda-97a8-11e6-8525-319b69ed8ab4.png">

**Comment by jakirkham** [comment]
Yeah, not sure if you are aware, but there is a large scale DDoS attack happening on Dyn DNS. This is impacting GitHub and a bunch of other things. So am not totally surprised that you are seeing this issue. Only recently workarounded it to get back online myself.

**Comment by nicoddemus** [comment]
Oh I didn't, thanks for the update @jakirkham

**Comment by goanpeca** [comment]
@jakirkham yep, I was aware of the attack :-|, but was not sure if this was related or not

**Comment by jakirkham** [comment]
Yep, saw similar with other Travis CI throughout the day. Have tried restarting now to see if it will work.

**Comment by jakirkham** [comment]
So the Travis CI builds appear to have uploaded the missing py3\* builds. I see all the Windows builds, but it looks like some of them were uploaded 4 hrs ago. In short, I think we are good on this issue, but please double check and let me know either way.

**Comment by goanpeca** [comment]
we are good. :-) thanks
